version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - 'mongo'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

  adminmongo:
    container_name: 'adminmongo'
    image: 'mrvautin/adminmongo'
    links:
      - 'mongo'
    environment:
      - HOST=0.0.0.0
    ports:
      - '1234:1234'
