version: "3"
services:
  app-eu:
    container_name: docker-node-mongo-eu
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "mongo-eu"
    links:
      - mongo-eu
    environment:
      VIRTUAL_HOST: api.empregourgente.com
      LETSENCRYPT_HOST: api.empregourgente.com
      LETSENCRYPT_EMAIL: joaopaulofurtado@live.com

  mongo-eu:
    container_name: mongo-eu
    image: mongo
    ports:
      - "27017:27017"

  admin-eu:
    container_name: admin-eu
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./admin:/usr/src/app
    depends_on:
      - "mongo-eu"
    links:
      - mongo-eu
    environment:
      VIRTUAL_HOST: admin.empregourgente.com
      LETSENCRYPT_HOST: admin.empregourgente.com
      LETSENCRYPT_EMAIL: joaopaulofurtado@live.com

  adminmongo-eu:
    container_name: "adminmongo-eu"
    image: "mrvautin/adminmongo"
    links:
      - "mongo-eu"
    depends_on:
      - "mongo-eu"
    environment:
      VIRTUAL_HOST: admin-mongo.empregourgente.com
      LETSENCRYPT_HOST: admin-mongo.empregourgente.com
      LETSENCRYPT_EMAIL: joaopaulofurtado@live.com
      HOST: 0.0.0.0
    ports:
      - "1234:1234"

networks:
  default:
    external:
      name: nginx-proxy
