####################################################
#*         DOCKER COMPOSE - DEVELOPMENT FILE
####################################################

version: "3"
services:
  node-api:
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "database"
    links:
      - database
    environment:
      VIRTUAL_HOST: api.empregourgente.com
      LETSENCRYPT_HOST: api.empregourgente.com
      LETSENCRYPT_EMAIL: joaopaulofurtado@live.com
    networks:
      - db-network

  database:
    container_name: database
    image: mongo
    ports: # these ports are commented out on production, so we don't have external connection in our db
      - "27017:27017"
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    networks:
      - db-network

  admin:
    container_name: admin
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./admin:/usr/src/app
    depends_on:
      - "database"
    links:
      - database
    environment:
      VIRTUAL_HOST: admin.empregourgente.com
      LETSENCRYPT_HOST: admin.empregourgente.com
      LETSENCRYPT_EMAIL: joaopaulofurtado@live.com

  admin-database:
    image: "mrvautin/adminmongo"
    links:
      - "database"
    depends_on:
      - "database"
    environment:
      VIRTUAL_HOST: admin-mongo.empregourgente.com
      LETSENCRYPT_HOST: admin-mongo.empregourgente.com
      LETSENCRYPT_EMAIL: joaopaulofurtado@live.com
      HOST: 0.0.0.0
    ports:
      - "3002:3002"

networks:
  default:
    external:
      name: nginx-proxy
  db-network:
    driver: bridge
