####################################################
#*         DOCKER COMPOSE - DEVELOPMENT FILE
####################################################

version: "3"
services:
  drogonbot-api:
    container_name: drogonbot-api
    restart: always
    build: .
    ports:
      - "$NODE_API_PORT:$NODE_API_PORT"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "drogonbot-database"
    links:
      - drogonbot-database
    environment:
      VIRTUAL_HOST: api.drogonbot.com
      LETSENCRYPT_HOST: api.drogonbot.com
      LETSENCRYPT_EMAIL: joaopaulofurtado@live.com
    networks:
      - db-network
      - default

  drogonbot-database:
    container_name: drogonbot-database
    image: mongo
    ports: # these ports are commented out on production, so we don't have external connection in our db
      - "$MONGO_PORT:$MONGO_PORT"
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    networks:
      - db-network

  # app-admin:
  #   container_name: app-admin
  #   build:
  #     context: ./admin
  #     dockerfile: Dockerfile
  #   ports:
  #     - "$NODE_ADMIN_PORT:$NODE_ADMIN_PORT"
  #   volumes:
  #     - ./admin:/usr/src/app
  #   depends_on:
  #     - "drogonbot-database"
  #   links:
  #     - drogonbot-database
  #   environment:
  #     VIRTUAL_HOST: admin.drogonbot.com
  #     LETSENCRYPT_HOST: admin.drogonbot.com
  #     LETSENCRYPT_EMAIL: joaopaulofurtado@live.com
  # app-admin-database:
  #   container_name: app-admin-database
  #   image: "mrvautin/adminmongo"
  #   links:
  #     - "drogonbot-database"
  #   depends_on:
  #     - "drogonbot-database"
  #   environment:
  #     VIRTUAL_HOST: admin-mongo.empregourgente.com
  #     LETSENCRYPT_HOST: admin-mongo.empregourgente.com
  #     LETSENCRYPT_EMAIL: joaopaulofurtado@live.com
  #     HOST: 0.0.0.0
  #   ports:
  #     - "$MONGO_ADMIN_PORT:$MONGO_ADMIN_PORT"
  # app-web:
  #   container_name: app-web
  #   restart: always
  #   build:
  #     context: ./app-web
  #     dockerfile: Dockerfile
  #   ports:
  #     - "$WEB_PORT:$WEB_PORT"
  #   volumes:
  #     - "./web:/usr/src/app"
  #     - "/web/node_modules/"
  #   depends_on:
  #     - "drogonbot-api"
  #     - "drogonbot-database"
  #   environment:
  #     VIRTUAL_HOST: empregourgente.com,vagasempregourgente.com
  #     LETSENCRYPT_HOST: empregourgente.com,vagasempregourgente.com
  #     LETSENCRYPT_EMAIL: joaopaulofurtado@live.com
  #   networks:
  #     - db-network

networks:
  default:
    external:
      name: nginx-proxy
  db-network:
    driver: bridge
