####################################################
#*         DOCKER COMPOSE - DEVELOPMENT FILE
####################################################

version: "3"
services:
  node-api:
    container_name: node-api
    restart: always
    build: .
    ports:
      - "$NODE_API_PORT:$NODE_API_PORT"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "node-database"
    links:
      - node-database
    environment:
      VIRTUAL_HOST: api.empregourgente.com
      LETSENCRYPT_HOST: api.empregourgente.com
      LETSENCRYPT_EMAIL: joaopaulofurtado@live.com
    networks:
      - db-network
      - default

  node-database:
    container_name: node-database
    image: mongo
    ports: # these ports are commented out on production, so we don't have external connection in our db
      - "$MONGO_PORT:$MONGO_PORT"
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    networks:
      - db-network

  node-admin:
    container_name: node-admin
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "$NODE_ADMIN_PORT:$NODE_ADMIN_PORT"
    volumes:
      - ./admin:/usr/src/app
    depends_on:
      - "node-database"
    links:
      - node-database
    environment:
      VIRTUAL_HOST: admin.empregourgente.com
      LETSENCRYPT_HOST: admin.empregourgente.com
      LETSENCRYPT_EMAIL: joaopaulofurtado@live.com

  node-admin-database:
    container_name: node-admin-database
    image: "mrvautin/adminmongo"
    links:
      - "node-database"
    depends_on:
      - "node-database"
    environment:
      VIRTUAL_HOST: admin-mongo.empregourgente.com
      LETSENCRYPT_HOST: admin-mongo.empregourgente.com
      LETSENCRYPT_EMAIL: joaopaulofurtado@live.com
      HOST: 0.0.0.0
    ports:
      - "$MONGO_ADMIN_PORT:$MONGO_ADMIN_PORT"

networks:
  default:
    external:
      name: nginx-proxy
  db-network:
    driver: bridge
