####################################################
#*         DOCKER COMPOSE - DEVELOPMENT FILE
####################################################

version: "3"
services:
  app-api:
    container_name: app-api
    restart: always
    build: .
    ports:
      - "$NODE_API_PORT:$NODE_API_PORT"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "app-database"
    links:
      - app-database
    environment:
      VIRTUAL_HOST: api.empregourgente.com
      LETSENCRYPT_HOST: api.empregourgente.com
      LETSENCRYPT_EMAIL: joaopaulofurtado@live.com
    networks:
      - db-network
      - default

  app-database:
    container_name: app-database
    image: mongo
    ports: # these ports are commented out on production, so we don't have external connection in our db
      - "$MONGO_PORT:$MONGO_PORT"
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    networks:
      - db-network

  app-admin:
    container_name: app-admin
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "$NODE_ADMIN_PORT:$NODE_ADMIN_PORT"
    volumes:
      - ./admin:/usr/src/app
    depends_on:
      - "app-database"
    links:
      - app-database
    environment:
      VIRTUAL_HOST: admin.empregourgente.com
      LETSENCRYPT_HOST: admin.empregourgente.com
      LETSENCRYPT_EMAIL: joaopaulofurtado@live.com

  # app-admin-database:
  #   container_name: app-admin-database
  #   image: "mrvautin/adminmongo"
  #   links:
  #     - "app-database"
  #   depends_on:
  #     - "app-database"
  #   environment:
  #     VIRTUAL_HOST: admin-mongo.empregourgente.com
  #     LETSENCRYPT_HOST: admin-mongo.empregourgente.com
  #     LETSENCRYPT_EMAIL: joaopaulofurtado@live.com
  #     HOST: 0.0.0.0
  #   ports:
  #     - "$MONGO_ADMIN_PORT:$MONGO_ADMIN_PORT"

  app-web:
    container_name: app-web
    restart: always
    build:
      context: ./app-web
      dockerfile: Dockerfile
    ports:
      - "$WEB_PORT:$WEB_PORT"
    volumes:
      - "./web:/usr/src/app"
      - "/web/node_modules/"
    depends_on:
      - "app-api"
      - "app-database"
    environment:
      ENV: ${ENV}
      VIRTUAL_HOST: empregourgente.com
      LETSENCRYPT_HOST: empregourgente.com
      LETSENCRYPT_EMAIL: joaopaulofurtado@live.com
    networks:
      - db-network

networks:
  default:
    external:
      name: nginx-proxy
  db-network:
    driver: bridge
