
export const DEFAULT_MAX_RISK_PER_TRADE = 1; // in %
export const DEFAULT_INITIAL_CAPITAL = 100000
export const DEFAULT_BROKER_COMISSION = 5;
export const DEFAULT_ATR_MULTIPLE = 3;


export const DEFAULT_LEVERAGE_MULTIPLE = 1

export const DEFAULT_LEVERAGE_INCREMENT_PER_PYRAMID_LAYER = 0.5;