
// More info: https://www.tradinggame.com.au/introduction-to-backtesting-metrics/

export interface IBackTest {
  initialCapital: number,
  finalCapital: number,
  expectancy: number, // most important factor!
  winPercentage: number,
  lossPercentage: number,
  maxDrawdown: number, // maximum drawdown is the largest peak-to-valley loss — in absolute Dollar terms — of the trading system’s historical profit.
  maxDrawdownPercentage: number,
  sharpRatio: number,
  profitFactor: number, // Profit factor is the system’s gross profit divided by gross loss. Look for systems that have a profit factor of 2.5, or higher.
  outlierAdjustedProfitFactor: number,
  maxConsecutiveWinners: number,
  maxConsecutiveLosers: number,
  totalDays: number, // at least 4 years of data
  totalTrades: number, // at least 20-25 trades
  grossProfit: number, // is the sum of points generated by all profitable trades
  grossLoss: number, // is the sum of points generated by all loss making trades
  totalNetProfit: number, // is gross profit minus gross loss
  totalNetProfitPercentage: number,
  averageProfitPerTrade: number,
  medianProfitPerTrade: number,
  largestSingleLosingTrade: number,
  largestSingleWinningTrade: number,
}